name: build-publish

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - v1.17.1

jobs:
  build:
    name: Docker build and publish
    runs-on: eg-default
    env:
      RELEASE_REGISTRY: kumo-docker-release-local.artylab.expedia.biz
      APP_NAME: istiod-debug
    steps:
      # For multi-platform builds
      - name: Set up Docker Buildx
        uses: actions/docker-setup-buildx-action@v2
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2
      - name: Go mod vendor
        run: |
          echo "SHA:"
          echo ${GITHUB_SHA}
          TEMP=$(mktemp -d)
          cp $HOME/.gitconfig $TEMP/.gitconfig
          HOME=$TEMP
          git config --global url."https://s-runtime-github:${{ secrets.RUN_GITHUB_TOKEN }}@github.expedia.biz".insteadOf "https://github.expedia.biz"
          go mod vendor
          HOME=$ORIG_HOME
      - name: Make
        run: |
          git config --add safe.directory /work
          make DEBUG=1 docker.pilot
      # Arty Login
      - name: Log in to ${{ env.RELEASE_REGISTRY }}
        uses: actions/docker-login-action@v2
        with:
          registry: ${{ env.RELEASE_REGISTRY }}
          username: ${{ secrets.KUMO_ARTY_SA_USER }}
          password: ${{ secrets.KUMO_ARTY_SA_PASSWORD }}
      - name: Docker push
        run: |
          docker image ls
          commit_sha=${GITHUB_SHA}
          releaseReg=${{ env.RELEASE_REGISTRY }}
          echo "Helo"
          echo ${commit_sha}
          echo ${releaseReg}
          docker tag istio/pilot:${commit_sha} ${releaseReg}/library/rcp-istio-debug:${commit_sha}
          docker image ls
          docker push ${releaseReg}/library/rcp-istio-debug:${commit_sha}